name: mbed CI

on:
  push:
    paths:
    - 'mbed/**'
    - '.github/workflows/mbed.yml'

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the mbed OS
      run: docker build -t mbed-os:latest -f mbed-os.dockerfile .
      working-directory: ./mbed
    - name: Build the mbed blinker application
      run: docker build -t mbed-blinker:latest -f mbed-blinker.dockerfile .
      working-directory: ./mbed

